@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd2ZXJhQHV2Lm14IiwiaHR0cHM6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Ikd1aWxsZXJtbyBWZXJhIiwiaHR0cHM6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckZlaUp3dCIsImF1ZCI6IkNsaWVudGVzRmVpSnd0IiwiaWF0IjoxNzMxMjY5ODk5LCJleHAiOjE3MzEyNzEwOTl9.Exg6Wwq1MyUNYiaUaZOjVbnqCnKrg6l3jDMk6C2RWfA

GET http://localhost:3000/api/categorias
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "gvera@uv.mx",
    "password": "patito"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "patito@uv.mx",
    "password": "patito"
}

###
GET http://localhost:3000/api/auth/tiempo
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/roles
Content-Type: application/json
Authorization: Bearer {{token}}